---
# Variable setup.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - nginx-setup

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags:
    - nginx-setup

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - nginx-setup

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - nginx-setup

# Vhost configuration.
- import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - validate nginx configuration
    - reload nginx
  tags:
    - nginx-setup

- name: Create /test location
  file:
    path: "{{nginx_root_path}}/test"
    state: directory
    mode: '0755'
  tags:
    - nginx-setup
  
- name: Copy index.html to /test
  template:
    src: "{{ nginx_testdir_indexfile }}"
    dest: "{{nginx_root_path}}/test/index.html"
    owner: "root"
    group: "root"
    mode: 0664
  tags:
    - nginx-setup
    - nginx-set-testfolder-items

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: started
    enabled: true
  tags:
    - nginx-setup