---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: nginx_yum_repo_enabled | bool

- name: Ensure nginx is installed.
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: insall nginx
  yum:
    name:
      - nginx
    state: latest
  tags:
    - nginx-setup

- name: Ensure nginx is installed.
  package:
    name: nginx
    state: present
  tags:
    - nginx-setup