FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html  /usr/share/nginx/html

ENV NGINX_VERSION=1.2
ENV NAME="SVS"

COPY entrypoint.sh entrypoint.sh

RUN chmod u+x entrypoint.sh

ENTRYPOINT ["bash", "-c"]
CMD [ ". entrypoint.sh" ]
#EXPOSE 8080