FROM alpine

RUN apk update

RUN apk add git

# By deffault gets itea-DevOps-base
ENV GIT_URL="https://github.com/Dgadavin/itea-base-course.git"


WORKDIR /data
VOLUME /data

CMD sh -c "git clone $GIT_URL"