---
# handlers file for nginx-role
- name: restart nginx
  service: name=nginx state=restarted
  tags:
    - nginx-setup
    - nginx-restart

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false
  tags:
    - nginx-setup
    - nginx-validate-conf

- name: Copy index.html to /test
  template:
    src: "{{ nginx_testdir_indexfile }}"
    dest: "{{nginx_root_path}}/test"
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_user }}"
    mode: 0664
  tags:
    - nginx-setup

- name: reload nginx
  service: name=nginx state=reloaded
  tags:
    - nging-reload
    - nginx-setup
